import CIMSymbol from "@arcgis/core/symbols/CIMSymbol";

export const jaringanEnergi: { [kode: string]: __esri.Symbol } = {
  "Saluran Udara Tegangan Ultra Tinggi (SUTUT)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [0, 90, 230, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 150, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Udara Tegangan Ekstra Tinggi (SUTET)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 0, 0, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 150, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Udara Tegangan Tinggi (SUTT)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [142, 103, 253, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 150, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Udara Tegangan Tinggi Arus Searah (SUTTAS)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [0, 230, 77, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 150, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Transmisi Lainnya": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 150, 0, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [135, 135, 135, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Udara Tegangan Menengah (SUTM)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [0, 90, 230, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 210, 30, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Udara Tegangan Rendah (SUTR)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 0, 0, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 210, 30, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Kabel Tegangan Menengah (SKTM)": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [142, 103, 253, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [255, 210, 30, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Saluran Distribusi Lainnya": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 210, 30, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [135, 135, 135, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jaringan Pipa/Kabel Bawah Laut Penyaluran Tenaga Listrik": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: -0.000002903178981104778,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 9,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: -300,
              ymin: -300,
              xmax: 300,
              ymax: 300,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [209, 178],
                      [31, -1],
                      [209, -179],
                      [178, -209],
                      [0, -32],
                      [-178, -209],
                      [-209, -179],
                      [-31, -1],
                      [-209, 177],
                      [-178, 208],
                      [0, 30],
                      [178, 209],
                      [209, 178],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 4,
                      width: 0,
                      color: [0, 0, 128, 217],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 150, 0, 255],
                    },
                  ],
                  angleAlignment: "Map",
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            rotateClockwise: false,
          },
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 7,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [0, 17],
                      [17, 17],
                      [17, 0],
                      [0, 0],
                      [0, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 4,
            color: [130, 70, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
};
