import CIMSymbol from "@arcgis/core/symbols/CIMSymbol";
import SimpleLineSymbol from "@arcgis/core/symbols/SimpleLineSymbol";

export const jaringanPrasaranaLain: { [kode: string]: __esri.Symbol } = {
  "Jaringan Air Baku": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: 0,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 3,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [8.5, 0],
                      [7.02, 0.13],
                      [5.59, 0.51],
                      [4.25, 1.14],
                      [3.04, 1.99],
                      [1.99, 3.04],
                      [1.14, 4.25],
                      [0.51, 5.59],
                      [0.13, 7.02],
                      [0, 8.5],
                      [0.13, 9.98],
                      [0.51, 11.41],
                      [1.14, 12.75],
                      [1.99, 13.96],
                      [3.04, 15.01],
                      [4.25, 15.86],
                      [5.59, 16.49],
                      [7.02, 16.87],
                      [8.5, 17],
                      [9.98, 16.87],
                      [11.41, 16.49],
                      [12.75, 15.86],
                      [13.96, 15.01],
                      [15.01, 13.96],
                      [15.86, 12.75],
                      [16.49, 11.41],
                      [16.87, 9.98],
                      [17, 8.5],
                      [16.87, 7.02],
                      [16.49, 5.59],
                      [15.86, 4.25],
                      [15.01, 3.04],
                      [13.96, 1.99],
                      [12.75, 1.14],
                      [11.41, 0.51],
                      [9.98, 0.13],
                      [8.5, 0],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [0, 77, 168, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            color: [0, 77, 168, 255],
          },
          {
            type: "CIMSolidStroke",
            effects: [
              {
                type: "CIMGeometricEffectDashes",
                dashTemplate: [6, 6],
                lineDashEnding: "HalfPattern",
                controlPointEnding: "HalfPattern",
              },
            ],
            enable: true,
            capStyle: "Butt",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 1,
            color: [0, 77, 168, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jaringan Produksi": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: 0,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 3,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [8.5, 0],
                      [7.02, 0.13],
                      [5.59, 0.51],
                      [4.25, 1.14],
                      [3.04, 1.99],
                      [1.99, 3.04],
                      [1.14, 4.25],
                      [0.51, 5.59],
                      [0.13, 7.02],
                      [0, 8.5],
                      [0.13, 9.98],
                      [0.51, 11.41],
                      [1.14, 12.75],
                      [1.99, 13.96],
                      [3.04, 15.01],
                      [4.25, 15.86],
                      [5.59, 16.49],
                      [7.02, 16.87],
                      [8.5, 17],
                      [9.98, 16.87],
                      [11.41, 16.49],
                      [12.75, 15.86],
                      [13.96, 15.01],
                      [15.01, 13.96],
                      [15.86, 12.75],
                      [16.49, 11.41],
                      [16.87, 9.98],
                      [17, 8.5],
                      [16.87, 7.02],
                      [16.49, 5.59],
                      [15.86, 4.25],
                      [15.01, 3.04],
                      [13.96, 1.99],
                      [12.75, 1.14],
                      [11.41, 0.51],
                      [9.98, 0.13],
                      [8.5, 0],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [0, 169, 230, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            color: [0, 169, 230, 255],
          },
          {
            type: "CIMSolidStroke",
            effects: [
              {
                type: "CIMGeometricEffectDashes",
                dashTemplate: [6, 6],
                lineDashEnding: "HalfPattern",
                controlPointEnding: "HalfPattern",
              },
            ],
            enable: true,
            capStyle: "Butt",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 1,
            color: [0, 169, 230, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Unit Distribusi": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: 0,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 4,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [8.5, 0],
                      [7.02, 0.13],
                      [5.59, 0.51],
                      [4.25, 1.14],
                      [3.04, 1.99],
                      [1.99, 3.04],
                      [1.14, 4.25],
                      [0.51, 5.59],
                      [0.13, 7.02],
                      [0, 8.5],
                      [0.13, 9.98],
                      [0.51, 11.41],
                      [1.14, 12.75],
                      [1.99, 13.96],
                      [3.04, 15.01],
                      [4.25, 15.86],
                      [5.59, 16.49],
                      [7.02, 16.87],
                      [8.5, 17],
                      [9.98, 16.87],
                      [11.41, 16.49],
                      [12.75, 15.86],
                      [13.96, 15.01],
                      [15.01, 13.96],
                      [15.86, 12.75],
                      [16.49, 11.41],
                      [16.87, 9.98],
                      [17, 8.5],
                      [16.87, 7.02],
                      [16.49, 5.59],
                      [15.86, 4.25],
                      [15.01, 3.04],
                      [13.96, 1.99],
                      [12.75, 1.14],
                      [11.41, 0.51],
                      [9.98, 0.13],
                      [8.5, 0],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 1,
                      color: [0, 92, 230, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [255, 255, 255, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            color: [0, 77, 168, 255],
          },
          {
            type: "CIMSolidStroke",
            effects: [
              {
                type: "CIMGeometricEffectDashes",
                dashTemplate: [6, 6],
                lineDashEnding: "HalfPattern",
                controlPointEnding: "HalfPattern",
              },
            ],
            enable: true,
            capStyle: "Butt",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 1,
            color: [0, 92, 230, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jaringan Sistem Pengelolaan Air Limbah Non Domestik": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: 0,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 4,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [8.5, 0],
                      [7.02, 0.13],
                      [5.59, 0.51],
                      [4.25, 1.14],
                      [3.04, 1.99],
                      [1.99, 3.04],
                      [1.14, 4.25],
                      [0.51, 5.59],
                      [0.13, 7.02],
                      [0, 8.5],
                      [0.13, 9.98],
                      [0.51, 11.41],
                      [1.14, 12.75],
                      [1.99, 13.96],
                      [3.04, 15.01],
                      [4.25, 15.86],
                      [5.59, 16.49],
                      [7.02, 16.87],
                      [8.5, 17],
                      [9.98, 16.87],
                      [11.41, 16.49],
                      [12.75, 15.86],
                      [13.96, 15.01],
                      [15.01, 13.96],
                      [15.86, 12.75],
                      [16.49, 11.41],
                      [16.87, 9.98],
                      [17, 8.5],
                      [16.87, 7.02],
                      [16.49, 5.59],
                      [15.86, 4.25],
                      [15.01, 3.04],
                      [13.96, 1.99],
                      [12.75, 1.14],
                      [11.41, 0.51],
                      [9.98, 0.13],
                      [8.5, 0],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [156, 156, 156, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            color: [0, 0, 0, 255],
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 1,
            color: [168, 112, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jaringan Sistem Pengelolaan Air Limbah Domestik": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPoint: {
              x: 0,
              y: 0,
            },
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 4,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 17,
              ymax: 17,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [8.5, 0],
                      [7.02, 0.13],
                      [5.59, 0.51],
                      [4.25, 1.14],
                      [3.04, 1.99],
                      [1.99, 3.04],
                      [1.14, 4.25],
                      [0.51, 5.59],
                      [0.13, 7.02],
                      [0, 8.5],
                      [0.13, 9.98],
                      [0.51, 11.41],
                      [1.14, 12.75],
                      [1.99, 13.96],
                      [3.04, 15.01],
                      [4.25, 15.86],
                      [5.59, 16.49],
                      [7.02, 16.87],
                      [8.5, 17],
                      [9.98, 16.87],
                      [11.41, 16.49],
                      [12.75, 15.86],
                      [13.96, 15.01],
                      [15.01, 13.96],
                      [15.86, 12.75],
                      [16.49, 11.41],
                      [16.87, 9.98],
                      [17, 8.5],
                      [16.87, 7.02],
                      [16.49, 5.59],
                      [15.86, 4.25],
                      [15.01, 3.04],
                      [13.96, 1.99],
                      [12.75, 1.14],
                      [11.41, 0.51],
                      [9.98, 0.13],
                      [8.5, 0],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [156, 156, 156, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
            markerPlacement: {
              type: "CIMMarkerPlacementAlongLineSameSize",
              angleToLine: true,
              offset: 0,
              controlPointsPlacement: "NoConstraint",
              customEndingOffset: 0,
              endings: "WithHalfGap",
              offsetAlongLine: 0,
              placementTemplate: [30, 30],
            },
            color: [0, 0, 0, 255],
          },
          {
            type: "CIMSolidStroke",
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 1,
            color: [156, 156, 156, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jalur Evakuasi Bencana": new SimpleLineSymbol({
    color: [255, 0, 255],
    width: 2,
    style: "short-dash",
  }),
  "Jaringan Drainase Primer": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMSolidStroke",
            effects: [
              {
                type: "CIMGeometricEffectWave",
                amplitude: 3,
                period: 5,
                seed: 1,
                waveform: "Sinus",
              },
            ],
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 2,
            color: [0, 76, 168, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jaringan Drainase Sekunder": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMSolidStroke",
            effects: [
              {
                type: "CIMGeometricEffectWave",
                amplitude: 3,
                period: 5,
                seed: 1,
                waveform: "Sinus",
              },
            ],
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 2,
            color: [255, 0, 0, 255],
          },
        ],
        animations: [],
      },
    },
  }),
  "Jaringan Drainase Tersier": new CIMSymbol({
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMLineSymbol",
        symbolLayers: [
          {
            type: "CIMSolidStroke",
            effects: [
              {
                type: "CIMGeometricEffectWave",
                amplitude: 3,
                period: 5,
                seed: 1,
                waveform: "Sinus",
              },
            ],
            enable: true,
            capStyle: "Round",
            joinStyle: "Round",
            lineStyle3D: "Strip",
            miterLimit: 10,
            width: 2,
            color: [169, 0, 230, 255],
          },
        ],
        animations: [],
      },
    },
  }),
};
